import turtle
"""
bob = turtle.Turtle()
bob.forward(100)
bob.left(45)
bob.forward(100)
bob.right(90)
bob.forward(100)
turtle.done()
"""
square = turtle.Turtle()

square.color("blue", "red")
square.begin_fill()
square.forward(100)
square.right(90)
square.forward(100)
square.right(90)
square.forward(100)
square.right(90)
square.forward(100)
square.end_fill()

square.penup()
square.forward(100)
square.pendown()

square.color("red", "blue")
square.begin_fill()
square.forward(100)
square.right(90)
square.forward(100)
square.right(90)
square.forward(100)
square.right(90)
square.forward(100)
square.end_fill()

square.penup()
square.forward(100)
square.pendown()

square.color("green", "yellow")
square.begin_fill()
square.forward(100)
square.right(90)
square.forward(100)
square.right(90)
square.forward(100)
square.right(90)
square.forward(100)
square.end_fill()


square.penup()
square.forward(100)
square.pendown()

square.color("yellow", "green")
square.begin_fill()
square.forward(100)
square.right(90)
square.forward(100)
square.right(90)
square.forward(100)
square.right(90)
square.forward(100)
square.end_fill()

turtle.done()